### ISSUE TITLE
开发环境下我下优化编译速度， 可以提供一下帮助吗

### ISSUE THREAD

**Issue by wxingheng** [localSummer/react-boilerplate-ie8#2]
开发环境下我下优化编译速度， 可以提供一下帮助吗

**Comment by localSummer** [comment]
简单从一下几个方面来优化一下吧
1. 优化webpack配置,抽离出公共代码,去掉不需要的依赖项,比如`vendor`中的fetch系列
2. 优化webpack插件配置

不过因为插件比较老,webpack版本比较低,所以性能上的牺牲多少会有的

**Comment by wxingheng** [comment]
`var proxy = require('proxy-middleware')
const url = require('url');
const proxyOptions = url.parse('http://192.168.110.85:9006/dic')
proxyOptions.route = '/dic'`


        proxy(proxyOptions)



搞定 proxy

**Comment by wxingheng** [comment]
优化了webpack的配置  现在编译大概需要  5s     以前基本是  1min

**Comment by localSummer** [comment]
@wxingheng 效率提高这么多，可以把你的配置合并进去哦，或者在下面展示一下，方便其他小伙伴参考使用

**Comment by wxingheng** [comment]
可以呀 ， 我明天整理一下   现在在我的项目里面

**Comment by wxingheng** [comment]
现在几乎是及时编译的， 1S

**Comment by localSummer** [comment]
@wxingheng 那就把这个issue关了，有新的优化可继续添加
