### ISSUE TITLE
npm run build后在ie可以运行的话，是不是说项目要部署在服务器上才可以在ie8上运行

### ISSUE THREAD

**Issue by lemonzoey** [localSummer/react-boilerplate-ie8#3]
看readme上说npm start在ie8上无法运行，我试了下在ie11上也没法运行。然后，若是npm run build后才能在ie8上运行，那是不是每次都要打包后部署到服务器，才能在ie8上看到效果呀？

**Comment by wxingheng** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    那你开发的时候就使用chrome 就好了，任何时候部署到服务器你都应该先打包。
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1228678518
                            
                    
                        
                            
                                    1228678518@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年06月18日 10:35，lemonzoey<notifications@github.com> 写道： 


看readme上说npm start在ie8上无法运行，我试了下在ie11上也没法运行。然后，若是npm run build后才能在ie8上运行，那是不是每次都要打包后部署到服务器，才能在ie8上看到效果呀？



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by lemonzoey** [comment]
那我要是想在ie8上调试代码，该如何处理呀？

**Comment by lemonzoey** [comment]
那我要是想在ie8上调试代码，该如何处理呀？

**Comment by localSummer** [comment]
IE8下是没有调试体验可言的，只需关注重点功能在IE上的可用，其他你可以正常在chrome开发，这样是没有问题的，然后在完成一个功能或一个模块时打包在IE上验证。
